# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Morey Wood
email: morey.wood@gmail.com
creator_name: Morey Wood
description: Graduate Computer Science student at Mississippi State University.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://moreywood.com" # the base hostname & protocol for your site
github_username:  moreyw
linkedin_username: moreywood
display_email: morey.wood@gmail.com
education:  I graduated Summa Cum Laude from Mississippi State University in May 2015 with a Bachelor of Science in Computer Science and am currently pursuing my Masters in Computer Science there.


# Build settings
markdown: kramdown
